# Generated by Django 3.2.12 on 2023-06-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220402_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'TO DO'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('BLOCK', 'BLOCK')], default='TO_DO', max_length=20),
        ),
    ]
